name: blueprint
x-configs:
  database_env: &database-env
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: dummy
  minio_env: &minio-env
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  rails_env: &rails-env
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: dummy
    RAILS_ENV: development
    RAILS_MAX_THREADS: 6
    REDIS_URL: redis://redis:6379/1
    ACTIVE_STORAGE_SERVICE: minio
    AWS_ACCESS_KEY_ID: minio
    AWS_SECRET_ACCESS_KEY: minio123
    AWS_REGION: us-east-1
    AWS_BUCKET: blueprint-development
    AWS_ENDPOINT: http://minio:9000
    AWS_FORCE_PATH_STYLE: "true"

services:
  postgres:
    image: postgres:latest
    environment:
      <<: *database-env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: blueprint
    command: ["/bin/bash", "-c", "rm -f tmp/pids/server.pid && bin/dev"]
    environment:
      <<: *rails-env
    volumes:
      - rails_tmp:/rails/tmp
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - minio
    stdin_open: true
    tty: true

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

  minio:
    image: minio/minio:latest
    environment:
      <<: *minio-env
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    depends_on:
      - postgres
      - redis
      - minio
    tty: true
    stdin_open: true
    environment:
      <<: *rails-env
    command: ["bundle", "exec", "sidekiq"]

volumes:
  minio_data:
  postgres_data:
  rails_tmp:
